"meta.welcome" = ["Welcome to the greatest dungeon crawler of all time!"]
"combat.encounter" = [
    "You encounter a lion!",
    "You stumble across a tiger!",
    "Oh no! It's a bear!",
    "Oh my, it's a dragon!"
]
"combat.slay" = ["You slay the beast with your {{weapon}}!", "Your {{weapon}} ends {{enemy}}'s life."]
